//! # erh_llm
//!
//! A unified abstraction layer for interacting with multiple LLM backends
//! (Ollama, MistralAI) with support for chat history persistence, embeddings,
//! optional tool/component registries, and query classification.

mod history;
mod composer;
pub mod provider;
mod ollama;
mod mistral;
//mod mistral_client;
#[cfg(feature = "anthropic")]
pub mod anthropic;
pub mod errors;
#[cfg(feature="tools")]
mod components;

pub use composer::{ComposedPrompt, PromptComposer};
pub use errors::{ErhLlmError, Result};
pub use provider::{LlmProvider, OllamaConfig, AnthropicConfig, MistralConfig};
pub use ollama::{OllamaProvider, ModelOptions};
#[cfg(feature="anthropic")]
pub use anthropic::{AnthropicProvider, AnthropicOptions};
pub use mistral::{MistralProvider, MistralOptions};
pub use history::HistoryConfig;
use serde::{Deserialize, Serialize};

use crate::history::HistoryTrait;

use log::{debug, warn};

use crate::history::History;
#[cfg(feature="tools")]
pub use crate::components::{ComponentRegistry, Component, tools::Tool as Tool, prompt::Prompt as Prompt, resource::Resource, sampling::Sampling};


/// Configuration for an LLM model, including its identifier and generation parameters.
#[derive(Debug, Clone, Serialize, Deserialize, Default,PartialEq)]
pub struct ModelConfig {
    /// The model identifier (e.g. `"mistral"`, `"llama3"`).
    pub model: String,
    /// An optional short display name for the model.
    pub short: Option<String>,
    /// Whether this model supports tool/function calling.
    pub tool: Option<bool>,
    /// Sampling temperature. Higher values produce more varied output.
    pub temperature: Option<f32>,
    /// Maximum context window size in tokens.
    pub context_size: Option<u32>,
}

impl ModelConfig {
    /// Creates a new [`ModelConfig`] with the given model identifier and all
    /// other fields set to their defaults.
    pub fn new(model: &str) -> Self {
        ModelConfig {
            model: model.to_string(),
            ..Default::default()
        }
    }
}

/// Represents a single exchange between a user and the bot, used for history persistence.
#[derive(Debug,Clone,Default)]
pub struct ChatMessage {
    /// Optional database row ID assigned after persistence.
    pub id: Option<i64>,
    /// Username or identifier of the human participant.
    pub user: String,
    /// The message sent by the user.
    pub user_message: String,
    /// The response generated by the bot.
    pub bot_response: String,
    /// Unix timestamp of when the message was created.
    pub timestamp: i64,
    /// UUID identifying the chat session this message belongs to.
    pub chatuuid: String,
}

impl ChatMessage {
    /// Returns `true` if the message has non-empty user and bot content,
    /// indicating it is suitable for persistence.
    pub fn validate(&mut self) -> bool {
        {
            !self.user_message.is_empty()
                && !self.bot_response.is_empty()
                //&& self.timestamp != 0
                //&& self.chatuuid.len() == 40
        }
    }

    /// Constructs a [`ChatMessage`] from a 4-tuple of
    /// `(user, user_message, bot_response, chatuuid)`.
    ///
    /// The `timestamp` field is left at `0` and should be set by the caller.
    pub fn from_tuple(tuple: (String,String, String, String)) -> Self {
        ChatMessage {
            user: tuple.0.clone(),
            user_message: tuple.1.clone(),
            bot_response: tuple.2.clone(),
            timestamp: 0, // Default value, should be set later
            chatuuid: tuple.3.clone(),
            ..Default::default()
        }
    }

    /// Returns a copy of this message with all emoji characters stripped from
    /// both `user_message` and `bot_response`.
    pub fn noemoji(&self) -> Self {
        let mut msg = self.clone();
        msg.user_message = demoji!(self.user_message);
        msg.bot_response = demoji!(self.bot_response);
        msg
    }

}

/// Identifies the LLM backend to connect to.
#[derive(Debug,Clone,PartialEq)]
pub enum LLM {
    /// A locally hosted Ollama instance. Fields: `(host, port, model_config)`.
    Ollama(String, u16, ModelConfig),
    /// The MistralAI cloud API. Contains the API key.
    MistralAI(String),
    /// The Anthropic Claude API. Contains the API key and model config.
    Anthropic(String, ModelConfig),
    /// Placeholder variant for future backends; panics if used.
    Dummy,
}

/// Wraps a prompt string with an optional model override.
pub enum UserPrompt {
    /// Use the model already configured on the [`Query`].
    Default(String),
    /// Override the model for this single request. Fields: `(model_config, prompt)`.
    Model(ModelConfig, String),
}

/// Holds all per-request configuration that governs how a query is sent to the LLM.
#[derive(Clone, Default)]
pub struct QuerySetup {
    /// Username or identifier of the human sending the query.
    pub user: String,
    /// UUID of the chat session, used to look up and store history.
    pub chatuuid: String,
    /// The model configuration to use for this query.
    pub model : ModelConfig,
    /// The raw user prompt text.
    pub prompt: String,
    /// Optional component/tool registry (only available with the `tools` feature).
    #[cfg(feature="tools")]
    pub components: Option<ComponentRegistry>,
    /// Optional style instruction appended to the prompt (e.g. `"formal"`, `"concise"`).
    pub style: Option<String>,
    /// Optional constraint appended to the prompt to restrict the model's output.
    pub constraint: Option<String>,
}

impl QuerySetup {
    /// Creates a new [`QuerySetup`] with all fields set to their defaults.
    pub fn new() -> Self {
        QuerySetup::default()
    }

}

impl Default for LLM {
    fn default() -> Self {
        LLM::Ollama("localhost".to_string(), 11434, ModelConfig::new("mistral"))
    }
}

/// The main entry point for sending prompts to an LLM backend.
///
/// A `Query` bundles together the backend connection, per-request setup,
/// optional chat history, optional RAG context, and model options. Use
/// [`Query::new`] to create an instance, populate [`Query::setup`] and
/// [`Query::context`], then call [`Query::execute`].
#[derive(Default)]
pub struct Query {
    /// The LLM backend this query will be sent to.
    connection: LLM,
    /// Per-request configuration (user, model, prompt, style, etc.).
    pub setup: QuerySetup,
    /// History backend used to persist and replay chat turns.
    pub(crate)  history: Option<History>,
    /// Optional RAG context injected before the user prompt.
    pub context: String,
    /// Low-level model generation options (temperature, repeat penalty, etc.).
    pub options: ModelOptions,
    /// Optional classification criteria used by [`Query::classify_query`].
    classification: Option<String>,
    /// Optional component/tool registry (only available with the `tools` feature).
    #[cfg(feature="tools")]
    pub components: Option<ComponentRegistry>,
    /// The database row ID of the last message stored in history.
    /// Populated after a successful [`Query::execute`], [`Query::send`], or
    /// [`Query::send_with_system`] call.  `None` if history is disabled or the
    /// backend did not return an ID.
    pub last_message_id: Option<i64>,
}

impl Query {
    /// Generates a vector embedding for the given `chunk` of text using an Ollama
    /// backend specified by `config`.
    ///
    /// # Arguments
    /// * `config` – A tuple of `(host, port, model_config)` identifying the Ollama
    ///   instance and model to use for embedding generation.
    /// * `chunk` – The text to embed.
    ///
    /// # Returns
    /// A vector of `f32` values representing the embedding, or an empty vector if
    /// the Ollama request fails.
    pub async fn embed(config:(String,u16,ModelConfig),chunk:String) -> Result<Vec<f32>> {
        let (url, port, model) = config;
        ollama::ollama_embed(&url, port, &model, chunk).await
    }

    /// Retrieves all stored [`ChatMessage`]s for the given session UUID from the
    /// specified history backend.
    ///
    /// This is a convenience static method that does not require an existing [`Query`]
    /// instance.
    pub async fn get_history(uuid: &str, history: HistoryConfig) -> Result<Vec<ChatMessage>> {
        let h = History::new(history);
        let msgs = h.read(uuid)?;
        Ok(msgs)
    }

    /// Sets the feedback value (`"U"` for thumbs-up, `"D"` for thumbs-down) on the
    /// `chat_history` row identified by `message_id`.
    ///
    /// # Errors
    /// Returns an error if the history backend is not configured or if the
    /// database update fails.
    pub async fn set_chat_feedback(message_id: i64, feedback: &str, history: HistoryConfig) -> Result<()> {
        let mut h = History::new(history);
        h.set_feedback(message_id, feedback)
    }
}

impl Query {
    /// Creates a new [`Query`] connected to the given LLM backend and configured
    /// to persist chat history using the provided [`HistoryConfig`].
    ///
    /// Pass [`HistoryConfig::None`] (or any unrecognised variant) to disable
    /// history persistence.
    pub fn new(connection: LLM, history: HistoryConfig) -> Self {
        let mut q = Query {
            connection,
            ..Default::default()
        };
        match history {
            HistoryConfig::Sqlite(db) => {
                debug!("Using SQLite history with database: {db}");
                q.history = Some(History::new(HistoryConfig::Sqlite(db)));
            }
            HistoryConfig::Mysql(config) => {
                debug!("Using MySQL history with config: {config:?}");
                q.history = Some(History::new(HistoryConfig::Mysql(config)));
            }
            HistoryConfig::MsSql(config) => {
                debug!("Using MSSQL history with config: {config:?}");
                q.history = Some(History::new(HistoryConfig::MsSql(config)));
            }
            _ => {
                q.history = None;
            }

        }
        q
    }


    /// Builds a fully formatted prompt from [`QuerySetup`] (constraint, context,
    /// user query, and style) and sends it to the configured LLM backend.
    ///
    /// The response is stored in the history backend (if configured) and returned
    /// as a `String`. Returns an empty string on send failure.
    pub async fn execute(&mut self) -> Result<String> {
        debug!("Running query with message: {}", self.setup.prompt);
        debug!("ComponentRegistry: {:?}", self.components.as_ref().map(|c| c.components.len()));

        let qsetup = self.setup.clone();

        let composed = PromptComposer::new()
            .context(self.context.clone())
            .constraint(qsetup.constraint.as_deref().unwrap_or(""))
            .style(qsetup.style.as_deref().unwrap_or(""))
            .build(&qsetup.prompt);

        debug!("System prompt: {}", composed.system);

        // Send the system prompt as a dedicated system turn so Ollama keeps
        // context, constraints and style clearly separated from the user query.
        let x = match self.send_with_system(composed.system, composed.user).await {
            Ok(result) => result,
            Err(e) => {
                log::error!("send_with_system failed: {e}");
                return Err(e);
            }
        };
        log::debug!("Query result: {x:?}");
        Ok(x)
    }

    /// Summarises the stored chat history for the current session into a compact
    /// paragraph, using the `mistral` model.
    ///
    /// # Returns
    /// A tuple `(latest_turn, summary)` where:
    /// * `latest_turn` is the most recent user/bot exchange formatted as plain text.
    /// * `summary` is an LLM-generated summary of all preceding turns, or an empty
    ///   string if there are fewer than two turns.
    ///
    /// Returns `("" , "")` when no history is available.
    async fn _summarize_history(&self) -> Result<(String, String)> {
        let mut history = if let Some(history) = &self.history {
            let history = history.read(&self.setup.chatuuid)?;
            if history.is_empty() {
                return Ok((String::new(), String::new()));
            }
            history
        } else {
            return Ok((String::new(), String::new()));
        };

        let latest = history.pop().unwrap();
        let result =if !history.is_empty() {
            let history_text: String = history.iter()
                .map(|msg| format!("USER: {}\nMESSAGE: {}\nRESPONSE: {}\n", msg.user, msg.user_message, msg.bot_response))
                .collect();
            let prompt = format!(
                "QUERY: Summarize the following chat history in a concise paragraph:\n\nCHAT_HISTORY: {history_text}\n",
            );
            self.send_raw(UserPrompt::Model(ModelConfig::new("mistral"), prompt)).await?
        } else {
            String::new()
        };

        let latest = format!("USER: {}\nMESSAGE: {}\nRESPONSE: {}\n", latest.user, latest.user_message, latest.bot_response);

        //debug!("Summarized history: {result}");
        Ok((latest,result))
    }

    /// Sends a raw prompt string to the LLM using the default model configuration,
    /// then persists the resulting [`ChatMessage`] to the history backend.
    ///
    /// Prefer [`Query::execute`] for structured queries that include context,
    /// constraints, and style. Use this method when you want to send an already
    /// assembled prompt directly.
    ///
    /// # Errors
    /// Returns an error if the LLM request fails or if history storage fails.
    pub async fn send(&mut self, prompt: String) -> Result<String> {
        let resp = self.send_raw(UserPrompt::Default(prompt)).await?;
        let mut msg = ChatMessage { id: None, user: self.setup.user.clone(), user_message: self.setup.prompt.clone(), bot_response: resp.clone(), timestamp: 0, chatuuid: self.setup.chatuuid.clone() };
        debug!("Storing message in history: {msg:?}");
        if let Some(history) = &mut self.history
            && let Err(e) = history.store(&mut msg) {
                warn!("Error storing message in history: {e}");
                return Err(e);
            }
        self.last_message_id = msg.id;
        Ok(resp)
    }

    /// Sends a system message and a user query to the LLM as separate role turns,
    /// then persists the exchange to history.
    ///
    /// This is the preferred path from [`Query::execute`]: the system message carries
    /// role, context, constraints and style; the user message contains only the raw
    /// query. Keeping them separate lets Ollama (and most instruction-tuned models)
    /// apply the system instructions without confusing them with conversational
    /// history.
    ///
    /// # Errors
    /// Returns an error if the LLM request or history storage fails.
    pub async fn send_with_system(&mut self, system: String, user_query: String) -> Result<String> {
        let resp = self.send_raw_with_system(system, user_query).await?;
        let mut msg = ChatMessage {
            id: None,
            user: self.setup.user.clone(),
            user_message: self.setup.prompt.clone(),
            bot_response: resp.clone(),
            timestamp: 0,
            chatuuid: self.setup.chatuuid.clone(),
        };
        debug!("Storing message in history: {msg:?}");
        if let Some(history) = &mut self.history
            && let Err(e) = history.store(&mut msg) {
                warn!("Error storing message in history: {e}");
                return Err(e);
            }
        self.last_message_id = msg.id;
        Ok(resp)
    }

    /// Reads the chat history for the current session from the persistence layer.
    ///
    /// Returns an empty vec when no history backend is configured.
    fn read_history(&self) -> Result<Vec<ChatMessage>> {
        if let Some(history) = &self.history {
            history.read(&self.setup.chatuuid)
        } else {
            Ok(vec![])
        }
    }

    /// Like [`Query::send_raw`] but prepends a `system` role message before the
    /// user turn. History is **not** written by this method.
    async fn send_raw_with_system(&self, system: String, user_query: String) -> Result<String> {
        let resp = match &self.connection {
            LLM::Ollama(host, port, model) => {
                let history = self.read_history()?;
                ollama::ollama_chat_with_system(
                    host, *port, model, history, self.options.clone(),
                    system, user_query,
                    #[cfg(feature = "tools")] self.components.as_ref(),
                ).await?
            }
            #[cfg(feature="anthropic")]
            LLM::Anthropic(api_key, model) => {
                let history = self.read_history()?;
                anthropic::anthropic_chat_with_system(
                    api_key, model, history, system, user_query,
                    None,  // thinking_budget
                    false, // cache_system
                    #[cfg(feature = "tools")] self.components.as_ref(),
                ).await?
            }
            // For other backends fall back to a single concatenated prompt.
            _ => {
                let fallback = format!("{system}\n\n{user_query}");
                self.send_raw(UserPrompt::Default(fallback)).await?
            }
        };
        debug!("Received response: {resp}");
        Ok(resp)
    }


    ///
    /// Chat history is read from the persistence layer and injected into the
    /// request (Ollama coordinator) so the model retains conversational context,
    /// but the new exchange is **not** stored. Use [`Query::send`] if you want
    /// automatic history persistence.
    ///
    /// # Errors
    /// Returns an error if the underlying LLM client reports a failure.
    pub async fn send_raw(&self, prompt: UserPrompt) -> Result<String> {
        let (text, _model) = match prompt {
            UserPrompt::Default(p) => (p, ModelConfig::default()),
            UserPrompt::Model(model, p) => (p, model),
        };
        let resp = match &self.connection {
            LLM::Ollama(host, port, model) => {
                let history = self.read_history()?;
                ollama::ollama_chat(
                    host, *port, model, history, self.options.clone(), text,
                    #[cfg(feature = "tools")] self.components.as_ref(),
                ).await?
            }
            LLM::MistralAI(apikey) => {
                let history = self.read_history()?;
                let client = mistral::MistralClient::new(apikey);
                let mut messages: Vec<mistral::Message> = history.iter().flat_map(|m| {
                    [mistral::Message::user(&m.user_message), mistral::Message::assistant(&m.bot_response)]
                }).collect();
                messages.push(mistral::Message::user(&text));
                let req = mistral::ChatRequest::new("mistral-medium-latest", messages);
                let resp = client.chat(req).await
                    .map_err(|e| ErhLlmError::MistralError(e.to_string()))?;
                resp.first_content()
                    .map(str::to_owned)
                    .ok_or_else(|| ErhLlmError::MistralError("Empty response from Mistral".into()))?
            }
            #[cfg(feature="anthropic")]
            LLM::Anthropic(api_key, model) => {
                let history = self.read_history()?;
                anthropic::anthropic_chat(
                    api_key, model, history, text,
                    None, // thinking_budget
                    #[cfg(feature = "tools")] self.components.as_ref(),
                ).await?
            }
            // Add other LLMs here as needed
            _ => return Err(ErhLlmError::ConfigError("LLM backend not supported".into())),
        };
        debug!("Received response: {resp}");
        Ok(resp)
    }

    /// Provider-agnostic streaming chat.
    ///
    /// Mirrors [`Query::execute`] but calls the backend's native streaming path
    /// instead of waiting for the full response.  `on_chunk` is invoked for every
    /// text delta as it arrives.  Returns the complete response text when the
    /// stream ends.
    ///
    /// Backends that do not yet implement native streaming fall back to a single
    /// `on_chunk` call with the full non-streamed response, so the caller's logic
    /// stays the same regardless of provider.
    pub async fn stream_execute(
        &mut self,
        on_chunk: &mut (dyn FnMut(String) + Send),
    ) -> Result<String> {
        let qsetup = self.setup.clone();
        let composed = PromptComposer::new()
            .context(self.context.clone())
            .constraint(qsetup.constraint.as_deref().unwrap_or(""))
            .style(qsetup.style.as_deref().unwrap_or(""))
            .build(&qsetup.prompt);

        let history = self.read_history()?;

        let resp = match &self.connection {
            LLM::Ollama(host, port, model) => {
                ollama::ollama_stream_chat_with_system(
                    host, *port, model, history,
                    self.options.clone(),
                    composed.system, composed.user,
                    on_chunk,
                    #[cfg(feature = "tools")] self.components.as_ref(),
                ).await?
            }
            #[cfg(feature = "anthropic")]
            LLM::Anthropic(api_key, model) => {
                let provider = anthropic::AnthropicProvider::with_api_key(api_key.clone());
                use crate::provider::LlmProvider;
                provider.stream_chat_with_system(
                    model, history,
                    anthropic::AnthropicOptions::default(),
                    composed.system, composed.user,
                    on_chunk,
                    #[cfg(feature = "tools")] self.components.as_ref(),
                ).await?
            }
            _ => {
                // Fallback: non-streaming execute, emit as a single chunk
                let full = self.send_raw_with_system(composed.system, composed.user).await?;
                on_chunk(full.clone());
                full
            }
        };

        // Persist the exchange in history
        let mut msg = ChatMessage {
            id: None,
            user: self.setup.user.clone(),
            user_message: self.setup.prompt.clone(),
            bot_response: resp.clone(),
            timestamp: 0,
            chatuuid: self.setup.chatuuid.clone(),
        };
        if let Some(history_store) = &mut self.history
            && let Err(e) = history_store.store(&mut msg)
        {
            warn!("Error storing streamed message in history: {e}");
        }
        self.last_message_id = msg.id;

        Ok(resp)
    }

    /// Classifies [`QuerySetup::prompt`] against the criteria stored in
    /// `self.classification`.
    ///
    /// Returns an empty string if no classification criteria have been set via
    /// [`Query::_classify`]. The raw LLM response is returned as-is; callers are
    /// responsible for parsing the result.
    pub async fn classify_query(&mut self) -> Result<String> {

        let r = if let Some(classification) = &self.classification {
            let prompt = format!("QUERY: Classify following prompt by these criteria: {}\n\nPROMPT: {}", classification, self.setup.prompt);
            self.send(prompt).await?
        } else {
            String::new()
        };
        // TODO: Error handling for classification
        Ok(r)
    }

    /// Sets the classification criteria and immediately runs [`Query::classify_query`].
    ///
    /// This is a convenience wrapper that stores `classification` on the query
    /// before delegating to [`Query::classify_query`].
    pub async fn _classify(&mut self, classification: String) -> Result<String> {
        self.classification = Some(classification);
        self.classify_query().await
    }

}



/// Strips all emoji characters from a string expression and returns a `String`.
///
/// Uses a regex that covers the most common Unicode emoji ranges: emoticons,
/// symbols & pictographs, transport & map symbols, and regional indicator flags.
///
/// # Example
/// ```rust
/// let clean = demoji!("Hello 🌍!");
/// assert_eq!(clean, "Hello !");
/// ```
#[macro_export]
macro_rules! demoji {
    ($string:expr) => {{
        use regex::Regex;
        let regex = Regex::new(concat!(
            "[",
            "\u{01F600}-\u{01F64F}", // emoticons
            "\u{01F300}-\u{01F5FF}", // symbols & pictographs
            "\u{01F680}-\u{01F6FF}", // transport & map symbols
            "\u{01F1E0}-\u{01F1FF}", // flags (iOS)
            "\u{002702}-\u{0027B0}",
            "\u{0024C2}-\u{01F251}",
            "]+",
        )).unwrap();
        regex.replace_all(&$string, "").to_string()
    }};
}
